apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autos-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: autos-service
      labels:
        app: autos-service
    spec:
      containers:
      - name: autos-service
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: freddybendezu/autos-service