apiVersion: apps/v1
kind: Deployment
metadata:
  name: autos-service
spec:
  selector:
      matchLabels:
        app: autos-services
        tier: backend
        track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: autos-service
        tier: backend
        track: stable        
    spec:
      containers:
        - name: autos-service
          image: freddybendezu/autos-service
          ports:
            - name: http
              containerPort: 8084