apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscia-service-config
  namespace: default
data:
  postgres_host: 10.19.255.14
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoscia-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: autoscia-service
      labels:
        app: autoscia-service
    spec:
      containers:
      - name: autoscia-service
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: autoscia-service-config
                key: postgres_host        
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: autoscia-config
                key: postgres_db        
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: autoscia-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: autoscia-config
                key: postgres_password
        image: gcr.io/PROJECT_ID/autoscia-service:BUILD_ID