apiVersion: v1
kind: ConfigMap
metadata:
  name: cotizacion-service-config
  namespace: default
data:
  pacifico_cotizacion_url: https://servicios.pacificotest.com.pe:7005/ECOM_CERT/EcommerceAuto/CotizacionWS/serviceRest/Cotizacion/generarCotizacionCompleta
  pacifico_cotizacion_user: pacifico
  pacifico_cotizacion_pass: seguros
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cotizacion-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cotizacion-service
      labels:
        app: cotizacion-service
    spec:
      containers:
      - name: cotizacion-service
        env:
          - name: PACIFICO_COTIZACION_URL
            valueFrom:
              configMapKeyRef:
                name: cotizacion-service-config
                key: pacifico_cotizacion_url
          - name: PACIFICO_COTIZACION_USER
            valueFrom:
              configMapKeyRef:
                name: cotizacion-service-config
                key: pacifico_cotizacion_user
          - name: PACIFICO_COTIZACION_PASS
            valueFrom:
              configMapKeyRef:
                name: cotizacion-service-config
                key: pacifico_cotizacion_pass                
        image: freddybendezu/cotizacion-service
