apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: produccion
data:
  postgres_db: USER
  postgres_user: admin
  postgres_password: c1oudc0w
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pv-claim
  namespace: produccion  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-db
  namespace: produccion  
spec:
  template:
    metadata:
      labels:
        app: user-db
    spec:
      volumes:
        - name: user-storage
          persistentVolumeClaim:
            claimName: user-pv-claim
      containers:
        - image: postgres
          name: user-db
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: postgres_db          
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: postgres_password                 
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: user-db
          volumeMounts:
            - name: user-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: produccion
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: user-db